# Generated by Django 4.1.3 on 2022-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_pic',
            field=models.TextField(default='./static/course_imgs/default_course_img.png'),
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
