# Generated by Django 4.1.3 on 2022-12-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_course_pic_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_pic',
            field=models.TextField(default='default_course_img.png'),
        ),
    ]
