# Generated by Django 4.1.3 on 2022-12-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='midlle_name',
            new_name='middle_name',
        ),
    ]
