# Generated by Django 4.1.3 on 2022-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_midlle_name_users_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_pic',
            field=models.ImageField(upload_to='static/course_imgs'),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.CharField(default='default_pfp.png', max_length=255),
        ),
    ]
