# Generated by Django 4.1.3 on 2022-12-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courses_course_pic_alter_users_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_pic',
            field=models.ImageField(default='default_course_img.png', upload_to='static/course_imgs'),
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(default='default_pfp.png', upload_to='static/pfps'),
        ),
    ]
