# Generated by Django 4.1.3 on 2022-12-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_courses_course_pic_alter_users_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_pic',
            field=models.ImageField(default='course_imgs/default_course_img.png', upload_to='course_imgs/'),
        ),
    ]
