# Generated by Django 4.1.3 on 2022-12-10 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courses_course_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='picture',
            field=models.ImageField(default='pfps/default_pfp.png', upload_to='pfps/'),
        ),
    ]
