# Generated by Django 4.1.3 on 2022-12-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_reviews_date_alter_users_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='multimedia_json',
        ),
    ]
