# Generated by Django 4.1.3 on 2022-12-12 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_pages_multimedia_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='difficulty',
            field=models.TextField(default='Легкий'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.TextField(default='3'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pass_num', models.IntegerField()),
                ('mistake_num', models.IntegerField()),
                ('task_num', models.IntegerField()),
                ('cur_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.pages')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.users')),
            ],
            options={
                'db_table': 'trackers',
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.users')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
