# Generated by Django 4.1.3 on 2022-12-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_courses_date_created_courses_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
            preserve_default=False,
        ),
    ]
