# Generated by Django 4.1.3 on 2022-12-13 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_pages_page_num_tickets_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackers',
            name='mistake_num',
        ),
        migrations.RemoveField(
            model_name='trackers',
            name='pass_num',
        ),
        migrations.RemoveField(
            model_name='trackers',
            name='task_num',
        ),
        migrations.AddField(
            model_name='trackers',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
            preserve_default=False,
        ),
    ]
